version: 0.1

phases:
  pre_build:
    commands:
      - echo Build completed on `date`
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - mvn package
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest .
      - docker tag 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest
