version: 0.1

phases:
  pre_build:
    commands:
      - echo Build completed on `date`
      - mvn package
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t petclinic .
      - docker tag petclinic:latest 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest
